- core/test/missingVariables.test.js
Je mets ici en évidence un problème de l'implé actuelle des missing variables. 
Qui a été introduit via ce commit je pense https://github.com/betagouv/publicodes/commit/d2865e8cd107385b2b8e0e07a8314bfeda08a03d. 
J'ai mis du temps à le trouver, dans ma base de code plus complexe. 
Ce qu'il se passe : 
- on veut calculer `voiture` 
- l'algo va vérifier son parent `transport` 
- c'est une somme, donc comme on le voulait, on n'évalue pas les missing de sa formule
- sauf qu'ensuite, on évalue `empreinte`, qui via une comparaison, fait appel à gabarit. À ce moment, on va alors explorer le parent de `gabarit` , mais sans l'optimisation. 
- on se retrouve alors avec les variables `avion`, aucunement pertinentes pour le calcul ici. 
@mquandalle on retrouve évidemment le fix simple dont on a parlé …
> New failing test for parent missing variables

- CHANGELOG.md
- packages/core/package.json
- packages/react-ui/package.json
- packages/react-ui/source/contexts.tsx
- packages/react-ui/source/rule/RulePage.tsx
- packages/react-ui/tsconfig.json
Required for the migration of mon-entreprise to vitejs 
https://github.com/betagouv/mon-entreprise/pull/1861
> Publish publicodes-react as ES Module

- packages/core/source/index.ts
- packages/core/source/mecanisms/inversion.ts
Un soucis est remonté dans l'utilisation de l'inversion numérique dans une base de règles tierce. Pour solutionner ça il suffisait de monter le nombre d'itérations.
Je propose donc ici d'ajouter le nombre d'itérations en option de `Engine`.
> Add ability to define max inversion iterations in engine options

- CHANGELOG.md
- packages/api/example.ts
- packages/api/package.json
- packages/api/source/index.ts
- packages/api/source/middleware/koa.ts
- packages/api/source/openapi.yaml
- packages/api/source/route/evaluate.ts
- packages/api/source/route/rules.ts
- packages/api/source/route/test/evaluate.test.ts
- packages/api/source/route/test/rules.test.ts
- packages/api/source/test-e2e/__snapshots__/index.test.ts.snap
- packages/api/source/test-e2e/index.test.ts
- packages/api/source/types.ts
- packages/api/tsconfig.json
- packages/api/tsup.config.ts
- packages/api/vitest.config.ts
- packages/core/package.json
- packages/react-ui/package.json
- website/src/pages/api-rest.mdx
- yarn.lock
-   Remplace le paramètre du middleware par un Engine (remplace `publicodesAPI(() => new Engine(rule))` par `publicodesAPI(new Engine(rule))`)
-   Les expressions acceptent des objets ou des tableaux d'objets
- Update to beta 41
> Retour api

- CHANGELOG.md
- package.json
- packages/api/package.json
- packages/api/source/route/test/evaluate.test.ts
- packages/api/source/route/test/rules.test.ts
- packages/api/source/test-e2e/index.test.ts
- packages/core/package.json
- packages/core/source/index.ts
- packages/core/source/parsePublicodes.ts
- packages/core/source/ruleUtils.ts
- packages/core/test/co2.yaml
- packages/core/test/cycles.test.js
- packages/core/test/inversion.test.js
- packages/core/test/library.test.js
- packages/core/test/mecanisms.test.ts
- packages/core/test/missingVariables.test.js
- packages/core/test/recalcul.test.ts
- packages/core/test/situation.test.ts
- packages/core/test/utils.ts
- packages/core/tsup.config.ts
- packages/react-ui/package.json
- website/docs/api.mdx
- website/docs/tutoriel.mdx
- website/src/components/Documentation.tsx
- website/src/components/Playground.tsx
- website/src/components/PublicodeExample.tsx
- website/src/pages/api-rest.mdx
- yarn.lock
> Supersedes #243 
Partial fix to #124
The idea here is to simply remove the yaml parser from the publicode bundle. 
It would be the responsability of the client to transform his object
representation (YAML, JSON) to a Javascript object when initialising the
Engine. 
What do you think ? 
This PR would be a breaking change of course. But as far as I know, very easily corrected by client libraries, that would benefit a lot : 
- for browser side publicode usage, the weight gain is 3/5 (!)
- for server side, the client can use its prefered yaml parser
> No yaml dependency 2

- CHANGELOG.md
- packages/api/package.json
- packages/core/package.json
- packages/core/source/evaluationUtils.ts
- packages/core/source/mecanisms/condition.ts
- packages/core/source/mecanisms/variablesManquantes.ts
- packages/core/test/missingVariables.test.js
- packages/react-ui/package.json
Avant : le score de la règle avec le par défaut était à 1, ce qui l'amenait à avoir un score inférieur ou égale aux règles du par défaut.
On souhaite au contraire que la règle apparaisse en premier dans les questions, les questions du par défaut n'étant posée que si on ne sait pas répondre exactement à la question initiale.
> Corrige le score des règle avec le mécanisme par défaut

- packages/core/source/rule.ts
- packages/core/test/missingVariables.test.js
Hello ! 
J'ai repéré un bug en bossant sur NGC, je propose juste cette petite correction mais pas sur que ce soit suffisant ?
Pb: une règle dont la valeur par défaut est 0 n'apparaissait pas dans les missing variables du parent (la question n'est alors pas posée) !
J'ai l'impression que ça correspond à [cette situation](https://publi.codes/studio/d%C3%A9penses-primeur?code=%0A%23+Bienvenue+dans+le+bac+%C3%A0+sable+du+langage+publicode+%21%0A%23+Pour+en+savoir+plus+sur+le+langage+%3A%0A%23+%3D%3E+https%3A%2F%2Fpubli.codes%2Fdocumentation%2Fprincipes-de-base%0A%0Aprix+.+carottes%3A+2%E2%82%AC%2Fkg%0Aprix+.+champignons%3A+5%E2%82%AC%2Fkg%0Aprix+.+avocat%3A%0A++question%3A+combien+%3F%0A++par+d%C3%A9faut%3A+0%0A%0Ad%C3%A9penses+primeur%3A%0A++somme%3A%0A++++-+prix+.+carottes+*+1.5+kg%0A++++-+p …
> 0 as a default value is allowed

- CHANGELOG.md
- packages/react-ui/source/rule/DeveloperAccordion.tsx
- packages/react-ui/source/rule/RulePage.tsx
Désormais, la situation est inférée depuis l'engine, plus besoin de la passer en argument de la documentation
fix #262
> Enlève `situation` de l'API de `RulePage`

- packages/react-ui/source/rule/RulePage.tsx
- website/src/components/Documentation.tsx
- website/src/components/Playground.tsx
The dev section is unnecessary in the tutorial, and it adds visual complexity while trying to understand the language :
This PR create an option `showDevSection` true by default, that is used to hide this section in the tutorial.
> Hide dev section of the doc in the tuto

- packages/react-ui/source/PublicodesBlock.tsx
- packages/react-ui/source/component/Accordion.tsx
- packages/react-ui/source/mecanisms/Operation.tsx
- packages/react-ui/source/mecanisms/Reference.tsx
- packages/react-ui/source/mecanisms/Situation.tsx
- packages/react-ui/source/mecanisms/common.tsx
- packages/react-ui/source/rule/DeveloperAccordion.tsx
- packages/react-ui/source/rule/Header.tsx
- packages/react-ui/source/rule/RuleSource.tsx
Points corrigés : 
* phrases incluant des emojis : les emojis sont dissimulés aux lecteurs d'écran
* ajout d' `aria-label` précisant l'action de certains liens
* révision de la hiérarchisation de certaines balises `<hx>`
* affiche les parenthèses en JSX (précédemment en CSS)
* modifie certaines balises `<span>` > `<div>` pour se conformer au validateur W3C
* retire `DimOverlay` qui nuisait à l'accessibilité des couleurs (contrastes)
* ajout d'attributs `aria-expanded` sur les boutons "Déplier/Replier"
> Correctifs RGAA 

- CHANGELOG.md
- packages/core/tsup.config.ts
- website/docs/tutoriel.mdx
The initial need was to use "publicodes" directly in the browser without using a bundler or a package manager. The documentation now reference the following snippet to run publicodes directly in the browser:
```html
<script src="https://unpkg.com/publicodes@next/dist/index.global.js"></script>
<script>
const Engine = window.publicodes.default
</script>
```
> Remove iife format

- CHANGELOG.md
- packages/api/package.json
- packages/core/package.json
- packages/core/source/mecanisms/recalcul.ts
- packages/react-ui/package.json
- packages/react-ui/source/rule/RulePage.tsx
**publicodes-react**
- Fix the display of explanations in the context of a recalul mecanism (the computed values where those of the base engine before)
**core**
- Recalcul mecanism now use the initial context to compute the values of overrides, instead of using the new one.
> Update to 1.0.0-beta.66

- website/docs/tutoriel.mdx
Changement de la source de l'import de { Rulelink } de 'publicodes' à 'publicodes-react' dans l'exemple du tutoriel.
> Correction de l'import de "RuleLink"  dans l'exemple du tutoriel

- CHANGELOG.md
- packages/api/package.json
- packages/core/package.json
- packages/core/source/index.ts
- packages/core/source/parse.ts
- packages/core/source/parseExpression.ts
- packages/core/test/parseExpression.test.ts
- packages/react-ui/package.json
This PR takes over from https://github.com/betagouv/publicodes/pull/368, exposing the function `parseExpression`.
Example of usage in publiopti : https://github.com/incubateur-ademe/publiopti/pull/12
Are you ok with this @johangirod and @mquandalle ?
> Feat(core): expose the parseExpression function

- packages/core/source/parseExpression.ts
Go back to a error messages in french to avoid the following CI error : https://github.com/betagouv/publicodes/actions/runs/5645005382/job/15289929508
> fix(core): switch back to french error messages

- CHANGELOG.md
- packages/api/package.json
- packages/core/package.json
- packages/react-ui/package.json
@EmileRolley @johangirod, suite à #374, j'ai oublié de mettre à jour la version (je le fais ici) et j'aimerais publier le nouveau paquet, du coup qques questions:
- L'upgrade de la version peut il se faire automatiquement ? Via une commande ? Je l'ai fait à la main ici
- Peut-on publier une nouvelle version sur nom à partir du moment ou nous sommes dans l'orga Publicodes ?
- J'ai des soucis avec Prettier visiblement pour le md, c'est un pb de mon côté ?
Peut etre un premier élément de réponse ici: https://github.com/betagouv/publicodes/actions/runs/6483400025/job/17604888653
La publication du paquet a fail car j'ai oublié d'upgrader la version?
> Passage à la version beta-77

- packages/core/src/mecanisms/operation.ts
- packages/core/test/mécanismes/date.yaml
> Fix date equality

- packages/rest-api/README.md
Correction de deux URLs obsolètes dans la documentation de l'API.
> fix(docs): Fix outdated URLs

- packages/react-ui/package.json
- packages/react-ui/src/rule/RulePage.tsx
- packages/react-ui/src/rule/RulesNav.tsx
- packages/react-ui/src/rule/RulesSearch.tsx
- website/docs/api/react-ui.mdx
- website/src/components/Documentation.tsx
- yarn.lock
This PR introduces a new dependency `fuse.js` for the fuzzy search but the component is disabled by default and lazy loaded so it shouldn't be a problem no?
> feat(react-ui): add a search bar

- website/docs/tools/optim.mdx
Je m'intéresse actuellement aux nouveaux mécanismes d'optimisation et il semble que la signature donnée en exemple n'est plus à jour.
Cette PR propose une mise à jour d'après la signature de la dernière version publiée.
> Met à jour l'exemple d'appel à constantFolding

- CHANGELOG.md
- packages/core/src/mecanisms/inversion.ts
- packages/core/test/inversion.test.js
- website-v2/src/routes/docs/mecanismes/+page.svelte.md
En rajoutant la possibilité de "borner" l'inversion numérique nous avons améliorer le temps de calcul d'environ 20%.
Il est parfois délicat de trouver un maximum, mais la seule utilisation de `min: 0` (c'est facile de savoir si une valeur doit être positive) permet déjà un gain de performance non négligeable sur nos calculs.
Par contre j'ai du mal à trouver une façon de tester réellement l'impact de min/max à travers les tests unitaires. Je suis preneur si vous avez une idée.
> Ajout des parametres min/max sur le mécanisme d'inversion numérique

- .changeset/light-rivers-clean.md
- package.json
- packages/core/src/engine/index.ts
- packages/core/src/mecanisms/inversion.ts
- packages/core/test/mécanismes/contexte.yaml
The subengines of the different context were not cleaned on situation update.
This should fix a number of issues originated in 1.3.2
fix #560
> fix(core): inversion numérique with contexte bug

- website/src/data/publicodes-packages.ts
- website/src/lib/component/publicode-packages.svelte
- website/src/lib/model/package-with-metadata.ts
Certaines descriptions récupérées via NPM ne sont pas dans un format propice à être affiché en baseline comme c'est le cas sur le site. Cette PR rajoute donc la possibilité de le rajouter à la main si nécessaire.
> fix(website): add missing description for npm packages

- .changeset/violet-coats-work.md
- packages/core/src/engine/index.ts
- packages/core/test/situation.test.ts
If there were no previous situation (first call to `setSituation`), the following `setSituation` calls would not properly reset situation. 
It is fixed now.
> fix(core): bug when calling setSituation with keepPreviousSituation

- .github/workflows/release.yaml
- package.json
The CHANGELOG generated by the release script was failing the CI because of badly formatted markdown.
This commit runs prettier on CHANGELOG after generating it.
> fix: release script generated CHANGELOG

- .changeset/free-emus-draw.md
- packages/core/src/AST/index.ts
- packages/core/src/engine/index.ts
- packages/core/src/engine/types.ts
- packages/core/src/index.ts
- packages/core/src/parsePossibilité.ts
- packages/core/src/parsePublicodes.ts
- packages/core/test/mecanisms.test.ts
- packages/core/test/unePossibilité.test.js
- packages/forms/src/evaluatedFormElement.test.ts
- website/src/lib/component/publicodes/create-engine.ts
- website/src/routes/docs/manuel/une-possibilite/+page.svelte.md
Fix breaking due to applicability evaluation of possibilites
In the new `une possibilité` mecanism, the engine evaluates the applicability of each possibility, in order to automatically select if there is only one possibility that is applicable.
This leads to difficult to debug issues rooted in cyclic evaluations not beeing handled well in the current version of the engine.
This patch fixes this issue by adding a `flag` option to filter out possibilities that are not applicable. This flag is set to `false` by default.
```ts
const engine = new Engine(rules, {
flag: { filterNotApplicablePossibilities: true },
})
```
This is temporary, and will be removed in the future when the engine will be able to handle cyclic evaluations.
> fix(core): fix une possibilité so that it is not breaking anymore

- .changeset/easy-phones-watch.md
- packages/forms/src/computeNextFields.ts
- packages/forms/src/evaluatedFormElement.test.ts
- packages/forms/src/formElement.test.ts
- packages/forms/src/formElement.ts
- packages/forms/src/index.ts
- website/src/routes/docs/guides/creer-un-simulateur/+page.svelte.md
- BREAKING: the `saisie` key is now under the `form` key
- BREAKING: the `orientation` key is now under the `form` key for possibilities
- It is possible to customize label and description of the input with the `label` and `description` keys
- It is possible to customize the order of questions in form with the `position` key
> feat(forms): new form metadata in publicodes rule

- .changeset/cuddly-turkeys-march.md
- .changeset/poor-falcons-matter.md
- packages/tools/src/serializeParsedRules.ts
- packages/tools/test/compilation/getModelFromSource.test.ts
- packages/tools/test/compilation/ruleTypes.test.ts
- packages/tools/test/serializeParsedRules.test.ts
Inline rules were added explicitely in the compiled output, which result in an error about already defined rules
> fix(tools): bug when compiling possibilities with inline rules

- packages/react-ui/src/contexts.tsx
- packages/react-ui/src/hooks.ts
- packages/react-ui/src/mecanisms/Reference.tsx
- packages/react-ui/src/mecanisms/common/NodeValueLeaf.tsx
- packages/react-ui/src/rule/RulePage.tsx
Objectif: permettre de cacher certaines valeurs pour des raisons de confidentialité. Le caractère privé de la variable ne suffisait pas / ne fonctionnait pas pour moi. Et je ne voulais pas me contraindre sur les restrictions d'utilisation de variables privées.
Avec les variables privées si on omet le pb de l'accès "pas partout", la page n'est pas accessible mais le chiffre visible
Preneur de os retours, sur l'idée, l'implé et le nom à afficher si masqué :)
> feat(react-ui): add "rulesToHide" option
