core/source/index.ts, core/source/parsePublicodes.ts, core/source/replacement.tsx, core/source/rule.ts
Un petit fix de types et du renommage anodin.
=> Publicodes typing naming

core/source/AST/index.ts, core/source/index.ts, core/source/mecanisms/recalcul.ts, core/source/replacement.tsx, core/source/ruleUtils.ts, docs/api.md, example/publicodes-react/src/Publicodes.js, site/components/Studio.tsx, ui-react/package.json, ui-react/source/Markdown.tsx, ui-react/source/RuleLink.tsx, ui-react/source/contexts.tsx, ui-react/source/index.tsx, ui-react/source/mecanisms/Recalcul.tsx, ui-react/source/rule/Header.tsx, ui-react/source/rule/Meta.tsx, ui-react/source/rule/References.tsx, ui-react/source/rule/RulePage.tsx, yarn.lock
Changes imported from https://github.com/betagouv/mon-entreprise/pull/1800
=> Make the documentation router agnostic

core/source/mecanisms/barème.ts, core/source/mecanisms/grille.ts
=> Prend en compte les variables manquantes de l'assiette des grilles et barèmes

core/package.json, core/source/AST/types.ts, core/source/format.ts, core/source/index.ts, core/source/mecanisms/recalcul.ts, core/source/mecanisms/situation.ts, core/source/rule.ts, core/test/missingVariables.test.js, core/test/recalcul.test.ts, core/webpack.config.js, ui-react/source/data/mecanisms.json, ui-react/source/data/mecanisms.yaml, ui-react/source/mecanisms/Variations.tsx, ui-react/source/rule/RulePage.tsx, yarn.lock
Cf. https://github.com/betagouv/mon-entreprise/pull/1665
=> Readability debuggability

README.md
Salut à vous !
J'étais en train de plonger dans le code de _nosgestesclimat_ et je suis arrivé ici sur _publicodes_.
En me baladant sur le README je suis tombé sur 2 liens cassés donc voilà une petite PR pour fixer ça :slightly_smiling_face: 
Bravo à vous pour ces projets très cools et utiles :+1:
=> :wrench: Fix README broken links

website/docs/mécanismes.mdx, website/package.json, website/yarn.lock
Waiting for a build time way to to it, see https://github.com/facebook/docusaurus/discussions/6009
react-markdown adds 133.3 minified (gzipped 44) https://bundlephobia.com/package/react-markdown@7.1.1
=> Add react-markdown runtime dep to display it

packages/core/package.json, packages/react-ui/package.json
=> Improve package scripts

README.md, website/docs/api.mdx, website/src/pages/communaute.md
confer https://github.com/betagouv/mon-entreprise/issues/1829
=> Update mon-entreprise URL

CHANGELOG.md, packages/core/package.json, packages/react-ui/package.json
=> Add a module meta-data in package.json

CHANGELOG.md, packages/core/package.json, packages/react-ui/package.json, packages/react-ui/react-shim.js
cf. https://github.com/egoist/tsup/issues/390
cf. https://github.com/betagouv/mon-entreprise/issues/1975
=> Inject JSX runtime for react

packages/core/test/mecanisms.test.ts, packages/core/test/mécanismes/conversion-unité.yaml
Les tests de mécanisme n'étaient pas lancés. C'est maintenant réparé.
=> Répare les tests de mécanisme

package.json, packages/core/.mocharc.json, packages/core/package.json, packages/core/source/AST/index.ts, packages/core/source/index.ts, packages/core/tsconfig.json, yarn.lock
=> Améliore l'utilisation des tests unitaires

CHANGELOG.md, packages/react-ui/source/mecanisms/common.tsx, website/docs/mécanismes.mdx, website/docs/principes-de-base.mdx, website/docusaurus.config.js, website/package.json, website/src/components/Documentation.tsx, website/src/components/PublicodeExample.tsx, website/src/components/publicodeExample.module.css, website/src/pages/index.mdx, website/src/plugins/match-publicodes.cjs, yarn.lock
=> Ajout d'un editeur live des exemples publicode

CHANGELOG.md, packages/core/source/mecanisms/plafond.ts, packages/react-ui/source/mecanisms/Unité.tsx
Fix #171
https://deploy-preview-174--publicodes-website.netlify.app/studio/?code=nombre+de+repas%3A+12+repas%2Fmois%0Aremboursement+forfaitaire%3A+4.21+%E2%82%AC%2Frepas%0Aremboursement+repas%3A%0A++valeur%3A+nombre+de+repas+*+remboursement+forfaitaire%0A++plafond%3A+120+%E2%82%AC%2Fan%0A++unit%C3%A9%3A+%E2%82%AC%2Fmois%0A++arrondi%3A+oui
=> Fix unit mechanism documentation

CHANGELOG.md, packages/core/package.json, packages/core/source/AST/types.ts, packages/core/source/evaluateApplicability.ts, packages/core/source/index.ts, packages/core/source/parsePublicodes.ts, packages/core/source/replacement.tsx, packages/core/source/rule.ts, packages/core/test/mecanisms.test.ts, packages/core/test/missingVariables.test.js, packages/core/test/mécanismes/expressions.yaml, packages/core/test/mécanismes/remplace.yaml, packages/react-ui/source/rule/RulePage.tsx, website/docs/api.mdx
=> Create a new applicability evaluation function

website/docusaurus.config.js, website/package.json, website/src/components/Documentation.tsx, website/src/components/Studio.tsx, website/src/pages/studio.tsx, website/src/plugins/studio-route.cjs, yarn.lock
fix #193
fix https://github.com/betagouv/mon-entreprise/issues/2094
=> Synchronise la target du bac à sable avec l'url et vice versa

website/src/components/Documentation.tsx
=> Avoid url replace when baseUrl is undefined

CHANGELOG.md, packages/api/package.json, packages/api/source/openapi.yaml, packages/core/package.json, packages/core/source/mecanisms/applicable.ts, packages/core/source/mecanisms/max-min.ts, packages/core/source/mecanisms/non-applicable.ts, packages/core/source/mecanisms/product.ts, packages/core/source/mecanisms/somme.tsx, packages/core/source/mecanisms/utils.ts, packages/core/test/mécanismes/le-maximum-de.yaml, packages/react-ui/package.json, yarn.lock
=> Fix bug in 'maximum de' and 'minimum de' mecanism

packages/core/source/ruleUtils.ts, packages/react-ui/package.json, packages/react-ui/source/RuleLink.tsx, packages/react-ui/source/icons/ArrowDown.tsx, packages/react-ui/source/icons/ArrowUp.tsx, packages/react-ui/source/icons/index.ts, packages/react-ui/source/rule/Header.tsx, packages/react-ui/source/rule/RulePage.tsx, packages/react-ui/source/rule/RuleSource.tsx, packages/react-ui/source/rule/RulesNav.tsx, website/package.json, website/src/components/Documentation.tsx, website/src/components/Studio.tsx, website/src/components/studio.module.css, yarn.lock
fix #242 
Exemple ici https://2237--mon-entreprise.netlify.app/documentation/dirigeant/auto%E2%80%91entrepreneur/chiffre-d'affaires
=> Ajout d'une arborescence des règles dans la documentation

CHANGELOG.md, packages/api/package.json, packages/api/source/openapi.yaml, packages/api/source/route/evaluate.ts, packages/api/source/route/test/__snapshots__/evaluate.test.ts.snap, packages/api/source/route/test/evaluate.test.ts, packages/api/source/test-e2e/__snapshots__/index.test.ts.snap, packages/api/source/test-e2e/index.test.ts, packages/core/package.json, packages/core/source/error.ts, packages/core/source/index.ts, packages/core/source/rule.ts, packages/core/source/ruleUtils.ts, packages/react-ui/package.json, packages/react-ui/source/RuleLink.tsx, packages/react-ui/source/mecanisms/Replacement.tsx, packages/react-ui/source/rule/DeveloperAccordion.tsx
Ce tag déclenche un warning quand la règle est utilisée via un appel API (dans evaluate ou dans setSituation).
=> Ajoute la gestion du tag `Experimental` pour les bases de règles

CHANGELOG.md, packages/api/package.json, packages/core/package.json, packages/react-ui/package.json, packages/react-ui/source/mecanisms/Operation.tsx, packages/react-ui/source/rule/DeveloperAccordion.tsx
Ajout des "Règles qui peuvent avoir un effet sur cette valeur"
=> Ajout dans la doc des regles qui sont modifié

packages/core/source/units.ts, packages/core/test/units.test.js
tentative d'ajout d'unité pour les distances
=> feat(core): Ajout des unité mm,cm,m,km

packages/api/README.md, packages/core/README.md, packages/react-ui/README.md
Let's start with the trivial issues 😅
Fixes #68
=> Add missing READMEs

CHANGELOG.md, packages/core/source/mecanisms/barème.ts, packages/core/source/mecanisms/grille.ts, packages/core/source/mecanisms/operation.ts, packages/core/source/mecanisms/tauxProgressif.ts, packages/core/test/mecanisms.test.ts, packages/core/test/mécanismes/barème.yaml, packages/core/test/mécanismes/opérations.yaml
This one was easy too. Fixes #41
=> Add an exception for division by zero

website/src/components/Studio.tsx
=> fix(Studio): fix doc link

.github/actions/install/action.yaml, .github/workflows/test.yaml
=> CI: test multiple node versions

website/docs/pourquoi-publicodes/_category_.yml, website/docs/pourquoi-publicodes/introduction.mdx, website/docs/pourquoi-publicodes/standard-modeles-ouverts.mdx, website/docs/standard-modeles-ouverts.mdx
https://deploy-preview-338--publicodes-website.netlify.app/docs/pourquoi-publicodes/standard-modeles-ouverts
=> Nouvelle page de doc exposant les principe de conception de modèles ouverts

website/src/components/Studio.tsx
=> fix(studio): use hash for urls

website/src/components/Studio.tsx
Remove le `#` préliminaire sinon ca en rajoute u à chaque fois
=> fix(studio): fix hash prefix

website/docs/guides/jeux-de-tests.mdx
proposition de guide sur le testing
=> docs: add testing example

CHANGELOG.md, packages/api/package.json, packages/core/package.json, packages/core/test/mécanismes/recalcul.yaml, packages/react-ui/package.json, packages/react-ui/source/rule/References.tsx, packages/react-ui/source/rule/RulePage.tsx, website/docs/api/react-ui.mdx
Following discussion in #90 and #87
=> Pass down prop 'dottedName' to 'Reference' component 

CHANGELOG.md, packages/api/package.json, packages/core/package.json, packages/react-ui/package.json, packages/react-ui/source/RuleLink.tsx, packages/react-ui/source/rule/DeveloperAccordion.tsx, packages/react-ui/source/rule/RuleSource.tsx
fix https://github.com/betagouv/mon-entreprise/issues/2509
=> Fix crash in doc page with private rule

CHANGELOG.md, packages/api/package.json, packages/core/package.json, packages/core/source/mecanisms/variablesManquantes.ts, packages/react-ui/package.json, packages/react-ui/source/Explanation.tsx
=> Update to 1.0.0-beta.70

website/docs/guides/model-template.mdx, website/docs/tools/_category_.yml, website/docs/tools/compilation.mdx, website/docs/tools/imports.mdx, website/docs/tools/index.mdx, website/docs/tools/optim.mdx, website/docs/tutoriel.mdx, website/docusaurus.config.js, website/src/pages/index.mdx
Adds documentation sections about `@publicodes/tools`, `@publicodes/language-server` and `@publicodes/model-template`.
=> Doc: update the documentation

CHANGELOG.md, packages/core/bench/index.ts, packages/core/package.json, packages/core/src/index.ts, packages/react-ui/package.json, packages/rest-api/package.json, yarn.lock
=> 1.0.0-rc.6

CHANGELOG.md, packages/core/package.json, packages/core/src/index.ts, packages/core/src/parsePublicodes.ts, packages/react-ui/package.json, packages/rest-api/package.json, website/docs/api/core.mdx
- Add a new engine option to disable the check of parent rule definition.
- Add documentation for the engine options in the website.
=> feat(core): add the `allowOrphanRules` engine option

packages/core/src/date.ts, packages/core/test/date.test.js
=> Support leap years

website/src/pages/index.mdx
Simplification mon-entreprise.
Typo mes aides vélo et complément, typo NGC.
MAJ futureco.
Temps présent pour Impact CO2, et description moins abstraite
=> Itération sur la description des items de "qui utilise publicodes"

CHANGELOG.md, packages/core/bench/contexte.ts, packages/core/package.json, packages/core/src/engine/index.ts, packages/core/src/mecanisms/contexte.ts, packages/core/src/parsePublicodes.ts, packages/core/test/situation.test.ts, packages/react-ui/package.json, packages/react-ui/src/RuleLink.tsx, packages/react-ui/src/mecanisms/Contexte.tsx, packages/react-ui/src/rule/RulePage.tsx, packages/rest-api/package.json, website/docs/tutoriel.mdx, yarn.lock
=> [🐛 bug] les règles du contexte ne devraient pas apparaître dans la situation

CHANGELOG.md, packages/core/package.json, packages/core/src/mecanisms/contexte.ts, packages/core/test/mécanismes/contexte.yaml, packages/react-ui/package.json, packages/rest-api/package.json
=> fix: critical bug with `context`

website-v2/src/lib/ui/nav-tab.svelte, website-v2/src/routes/+layout.svelte
Just un bold mais première approche svelte 😅
=> feat: highlight current tab in nav

website-v2/src/lib/ui/nav-tab.svelte
=> [✨ Website V2] Fix nav highlighting

website-v2/src/lib/PublicodesEditor/index.svelte, website-v2/src/lib/ui/button.svelte, website-v2/src/lib/ui/card.svelte, website-v2/src/routes/+layout.svelte, website-v2/src/routes/+page.svelte, website-v2/tailwind.config.js
Pour avoir plus facilement la main 
J'ai utilisé https://uicolors.app/create à partir de `#2975d1` du logo
Et je propose violet pour la couleur secondaire si besoin (pas du tout parce que j'adore le violet 😂)
=> [✨ Website V2] feat: add and use custom color palette

website-v2/src/routes/+page.svelte
J'avoue en vrai c'est juste pour tester si Vercel va déployer une preview sans faire payer.
=> Add a link to the VSCode extension

CHANGELOG.md, packages/core/package.json, packages/core/src/engine/utils.ts, packages/core/test/situation.test.ts, packages/react-ui/package.json, packages/rest-api/package.json
Repéré sur NGC .. On manquait une partie du filtre 🥲
=> 🐛 fix: detect rules from `possibilités` if defined in `formule`

packages/react-ui/src/rule/RuleSource.tsx
Je pense que même en développement on souhaite tester les règles dans la version en prod du studio non ?
=> fix(react-ui): always import rules in the prod website

CHANGELOG.md, packages/core/package.json, packages/core/src/grammar.ne, packages/core/src/mecanisms/operation.ts, packages/core/test/mécanismes/expressions.yaml, packages/core/test/mécanismes/opérations.yaml, packages/core/test/parseExpression.test.ts, packages/react-ui/package.json, packages/rest-api/package.json
Close #529 
Un premier test de PR vers ce projet dans l'optique d'implémenter des calculs financiers basiques.
=> Ajout du mécanisme puissance

website/src/routes/docs/guides/elm/+page.svelte.md, website/src/routes/docs/guides/migration-v1/+page.svelte.md, website/svelte.config.js
Première version du guide d'utilisation de Publicodes depuis une application Elm. J'ai également créé un template correspondant : https://github.com/publicodes/elm-app-example
=> feat(guide): Publicodes avec elm

website/package.json, website/src/lib/search/insert-docsearch.ts, website/src/lib/ui/button.svelte, website/src/lib/ui/nav-tab.svelte, website/src/routes/+layout.svelte, website/src/routes/+page.svelte, yarn.lock
=> feat(website): add search

CHANGELOG.md, CODE_OF_CONDUCT.md, publiccode.yml
see https://yml.publiccode.tools/
fix #544
=> chore: add publiccode.yml file

.changeset/old-spoons-end.md, examples/nextjs/pages/[...slug].jsx, packages/react-ui/src/RuleLink.tsx, packages/react-ui/src/component/Accordion.tsx, packages/react-ui/src/component/Code.tsx, packages/react-ui/src/component/icons/Arrow.tsx, packages/react-ui/src/component/icons/Close.tsx, packages/react-ui/src/component/index.ts, packages/react-ui/src/contexts.tsx, packages/react-ui/src/rule/DeveloperAccordion.tsx, packages/react-ui/src/rule/RuleSource.tsx, packages/react-ui/src/rule/RulesNav.tsx
Multiple improvement on accessibility :
- Change level of title inside accordion
- Increase constrate on Copy button
- Implement [Aria Dialog pattern](https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/) on mobile menu
- Use proper ul/li imbrication on menu
- Use title instead of aria label to specify that link open in a new window
=> chore(react-ui): Improve accessibility

.changeset/nice-eagles-look.md, packages/core/src/grammar.ne, packages/core/src/mecanisms/operation.ts, packages/core/src/units.ts, packages/core/test/mécanismes/expressions.yaml, packages/core/test/mécanismes/opérations.yaml, packages/core/test/parseExpression.test.ts, website/src/routes/docs/manuel/types/+page.svelte.md
- Nouvelle opération division entière. Je me suis grandement inspiré de #530 
Preneur d'avis sur ce qu'il faut faire pour que ça soit intégré.
=> Ajout de l'opération division entière

website/src/routes/docs/manuel/principe-de-base/+page.svelte.md
Transformation d'un « à » en « a »
=> Correction d'une coquille

packages/tools/src/commands/init.ts, website/src/routes/docs/guides/creer-un-modele/+page.svelte.md
- Some fixes
- Add prettier
- Add bench and LS config for vscode in toolinbg options
=> feat: improve tools/init

.changeset/lucky-seahorses-leave.md, packages/forms/README.md, packages/forms/src/buildFormPage.ts, packages/forms/src/evaluatedFormElement.test.ts, packages/forms/src/evaluatedFormElement.ts, packages/forms/src/form.ts, packages/forms/src/formElement.ts, packages/forms/src/index.ts
Using interface instead of type intersection
https://github.com/microsoft/TypeScript/wiki/Performance
=> fix(forms): TS performance

.changeset/sixty-baboons-sell.md, packages/core/src/parsePublicodes.ts
fix #661 
Je ne vois pas comment ajouter un test ?
=> fix: RawRule can be `null`

.changeset/cruel-keys-nail.md, packages/core/src/mecanisms/contexte.ts, packages/core/test/missingVariables.test.js
=> fix(core):  contexte rules can't be missing

.changeset/clever-hoops-slide.md, .changeset/cruel-keys-nail.md, packages/core/src/mecanisms/contexte.ts, packages/core/test/missingVariables.test.js
=> fix(core): contexte rules can't be missing again

packages/compiler/lib/dependency_graph/cycle_check.ml, packages/compiler/lib/dependency_graph/extract_parameters.ml, packages/compiler/lib/eval/type_check.ml, packages/compiler/lib/parser/expr/lexer.ml, packages/compiler/lib/parser/expr/parser.ml, packages/compiler/lib/parser/parse.ml, packages/compiler/lib/parser/parse_value.ml, packages/compiler/lib/parser/parser_utils.ml, packages/compiler/lib/resolver/resolver.ml, packages/compiler/lib/utils/code_error.ml, packages/compiler/lib/utils/err.ml, packages/compiler/lib/utils/log.ml, packages/compiler/lib/utils/log.mli, packages/compiler/lib/utils/output.ml, packages/compiler/lib/yaml_parser/parse.ml
In this PR:
- refactoring of the `Log` module to handle more information in order to correctly create `Grace.Diagnostics`.
- addition of code errors and messages in the dedicated module `Err`. 
For now, diagnostics aren't precise as expected. However, before fixing this, I'll set up cram tests in a separated PR to simplify the process.
=> [V2] Better diagnostics

.changeset/breezy-bats-serve.md, packages/forms/src/buildFormPage.ts, packages/forms/src/computeNextFields.test.ts, packages/forms/src/computeNextFields.ts, packages/forms/src/evaluatedFormElement.test.ts, packages/forms/src/evaluatedFormElement.ts, packages/forms/src/formBuilder.test.ts, packages/forms/src/formBuilder.ts, packages/forms/src/formElement.test.ts, packages/forms/src/formElement.ts, packages/forms/src/groupByNamespace.test.ts, packages/forms/src/groupByNamespace.ts
Je suis pas sûr de moi du tout, notamment sur :
- La définition de `FormOptions` et la valeur par défaut pour pageBuilder
- Le fait que titre soit optionnel et donc que le titre soit mise à dispo de manière optionnelle dans `currentPage` alors que sa définition dépend du pageBuilder
=> feat(form): fix types, test and add title feature
